### ISSUE TITLE
mlstm_kernels installation error

### ISSUE THREAD

**Issue by jjihwan** [NX-AI/xlstm#69]
Awesome work!
I'm trying to install mlstm-kernels on ubuntu using venv, but I'm encountering the following error:
I'm using python==3.10.12 and pip==25.0.1.
Can u recommend any solutions to resolve this error?

```bash
~~/xlstm# pip3 install mlstm-kernels
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement mlstm-kernels (from versions: none)
ERROR: No matching distribution found for mlstm-kernels
```

**Comment by ai-bits** [comment]
I'm using the recommended Python 3.11 (Anaconda env) and I find ALL Requirements mlstm-kernels already satisfied (by pip install xlstm), so if you can't pip it it should not matter, but I got all kinds of other problems beyond the very basic.

`conda create -n xlstm python=3.11`
`conda activate xlstm`
`pip install -e . #rather than xlstm`
`pip install mlstm_kernels #all: Requirement already satisfied`
`pip install git+https://git@github.com/NX-AI/transformers.git@integrate_xlstm#egg=transformers`
`pip install accelerate>=0.26.0 #not mentioned`

May I ask what you DID get to run?
Cheers
G.

**Comment by maximilianmbeck** [comment]
Thanks @ai-bits for the detailed answer. 

The problem that you observed (@jjihwan) should be solved when switching to python 3.11 as this is a requirement for mlstm_kernels. 
The solution that @ai-bits provided should solve your problem. 

Let us know if you observe other problems.

**Comment by jjihwan** [comment]
Thank you for your kind response. I'll check the python version later.
I'll let you know and reopen this issue if the problem is not solved with python version.
